Fix macOS bind() name collision in Network.cpp
On macOS with 'using namespace std;', the socket bind() function
collides with std::bind from <algorithm>. Fixed by using ::bind()
to explicitly call the POSIX socket bind function.

This fixes the compilation error on Apple Silicon:
error: value of type '__bind<int &, sockaddr *, unsigned long>'
is not contextually convertible to 'bool'